services:
  flask-app:
    environment:
      - FLASK_ENV=test
      - FLASK_APP=api.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      - PYTHONUNBUFFERED=1
      - WATCHFILES_FORCE_POLLING=true

  vue-frontend:
    environment:
      - NODE_ENV=test
      - VITE_API_URL=http://flask-app:5000

  playwright-tests:
    image: mcr.microsoft.com/playwright:v1.51.0
    depends_on:
      - vue-frontend
      - flask-app
    environment:
      - BASE_URL=http://vue-frontend:5173
    working_dir: /app/vue-frontend
    volumes:
      - .:/app
    command: ["tail", "-f", "/dev/null"]
    # command: ["npx", "playwright", "test"]
