services:
  flask-app:
    build:
      context: flask-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./flask-backend:/app # For development and live reload
    environment:
      - FLASK_ENV=development
      - FLASK_APP=api.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      - PYTHONUNBUFFERED=1
      - WATCHFILES_FORCE_POLLING=true # Force Flask to detect file changes

  vue-frontend:
    build:
      context: vue-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./vue-frontend:/app # Sync local files for live reload
      - /app/node_modules # Prevent node_modules from syncing
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true # Force Vite to detect file changes
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - flask-app
