# Used in ci.yml to override default docker-compose.yml settings for GitHub Actions

services:
  flask-app:
    environment:
      - FLASK_ENV=test
      - FLASK_APP=api.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      - PYTHONUNBUFFERED=1
      - WATCHFILES_FORCE_POLLING=true

  vue-frontend:
    environment:
      - NODE_ENV=test
      - VITE_API_URL=http://flask-app:5000

  playwright:
    image: mcr.microsoft.com/playwright:latest
    depends_on:
      - flask-app
      - vue-frontend
    environment:
      - BASE_URL=http://vue-frontend:5173
    volumes:
      - ./vue-frontend:/app
    working_dir: /app
    # keep the container running
    command: ["tail", "-f", "/dev/null"]
