name: CI Pipeline
# on:
#   pull_request:
#     branches:
#       - main
#   push:
#     branches:
#       - main

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20 # Max timeout for the job in minutes

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker compose -f docker-compose.yml -f docker-compose.gh.actions.yml up --build -d

      - name: Wait for Services to be Ready
        run: |
          echo "Waiting for services to start..."
          sleep 10  # Adjust based on startup time

      - name: Run Backend Tests
        run: docker compose exec flask-app pytest

      - name: Install Node Dependencies for Playwright
        run: docker compose exec playwright npm install

      - name: Install Playwright Browsers
        run: docker compose exec playwright npx playwright install

      - name: Run Playwright Tests
        run: docker compose exec playwright npx playwright test

      - name: Capture Docker logs
        if: always()
        run: docker compose logs > docker-compose.log

      - name: Save log file to artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: docker-compose-log
          path: docker-compose.log

      - name: Stop and Clean up Docker
        if: always()
        run: docker compose down -v
