name: CI Pipeline
# on:
#   pull_request:
#     branches:
#       - main
#   push:
#     branches:
#       - main

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker compose -f docker-compose.yml -f docker-compose.gh.actions.yml up --build --abort-on-container-exit

      - name: Stop and Clean up Docker
        run: docker compose down -v
